//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(AlumnosDataAnotations))]
    public partial class Alumnos
    {
        public int idAlumnos { get; set; }
        public string nombre { get; set; }
        public string primerApellido { get; set; }
        public string segundoApellido { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string curp { get; set; }
        public Nullable<decimal> sueldo { get; set; }
        public int idEstadoOrigen { get; set; }
        public short idEstatus { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual EstatusAlumnos EstatusAlumnos { get; set; }
    }
    public partial class AlumnosDataAnotations
    {
        public int idAlumnos { get; set; }
        [Required(ErrorMessage = "El {0} es obligatorio")]
        [StringLength(40, MinimumLength = 3, ErrorMessage = "El {0} debe tener mínmo {2} caracteres y máximo {1} caracteres")]
        [DataType(DataType.Text)]
        public string nombre { get; set; }
        [MaxLength(40, ErrorMessage = "La longitud maxima del {0} es {1}")]
        [MinLength(3, ErrorMessage = "La longitud minima del {0} es {1}")]
        [Required(ErrorMessage = "El {0} es obligatorio")]
        [Display(Name = "apellido paterno")]
        public string primerApellido { get; set; }
        public string segundoApellido { get; set; }
        [Required(ErrorMessage = "El {0} es obligatorio")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Formato incorrecto")]
        public string correo { get; set; }
        [RegularExpression("[0-9]{10}", ErrorMessage = "El {0} debe ser de 10 digitos")]

        public string telefono { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime fechaNacimiento { get; set; }
        [RegularExpression("[A-Z]{4}[0-9]{6}[H|M][A-Z]{2}[B-DF-HJ-NP-TV-Z]{3}[A-Z&0-9]{2}", ErrorMessage = "El {0} no tiene el formato correcto")]
        public string curp { get; set; }
        public Nullable<decimal> sueldo { get; set; }
        public int idEstadoOrigen { get; set; }
        public short idEstatus { get; set; }

        public virtual Estados Estados { get; set; }
        public virtual EstatusAlumnos EstatusAlumnos { get; set; }
    }
}